version: '3.8'

services:
  # Container chuyên chạy Python Web Scraper
  real-estate-scraper:
    build: .
    container_name: vn_real_estate_scraper
    restart: unless-stopped
    # Mount toàn bộ source code vào để test ngay không cần build lại
    volumes:
      - .:/app
    env_file:
      - .env

    deploy:
      resources:
        limits:
          memory: 4G

    command: [ "python", "main.py", "--source", "all" ]
